version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VIMRC_PATH=${VIMRC_PATH:-.vimrc.example}
    ports:
      - ${NEXT_FORWARD_PORT:-3000}:3000
    volumes:
      - .:/usr/src/app
      - ~/.gitconfig:/etc/gitconfig
    working_dir: /usr/src/app
    tty: true
